version: '3'

services:
  repository-db:
    image: ireceptor/repository-mongodb:master
    volumes:
        - ./data/mongodb:/data/db:delegated
    environment:
        MONGO_INITDB_DATABASE: ireceptor
    restart: always

  repository:
    image: ireceptor/service-php-mongodb:master
    environment:
        DB_HOST: repository-db
        DB_DATABASE: ireceptor
        DB_SAMPLES_COLLECTION: sample
        DB_SEQUENCES_COLLECTION: sequence
        IRECEPTOR_AIRR_MAPPING_FILE: files/AIRR-iReceptorMapping.txt
    volumes:
        - ./config/turnkey:/var/www/html/config/files:delegated
    depends_on:
      - repository-db
    restart: always

  middleware:
    image: irpinesctec/adc-middleware:latest
    volumes:
      - ./config/middleware:/middleware/config
    environment:
      - UMA_CLIENT_SECRET=$MIDDLEWARE_UMA_CLIENT_SECRET
      - DB_PASSWORD=password
      - PROPERTIES_PATH=/middleware/config/example.properties
    depends_on:
      - keycloak
      - middleware-db
      - middleware-redis
    restart: always

  keycloak:
    build:
      context: ../keycloak
      dockerfile: Dockerfile
    volumes:
      ./keycloak/realm-export.json:/tmp/realm-export.json
    environment:
      DB_VENDOR: postgres
      DB_ADDR: keycloak_db
      DB_DATABASE: keycloak_db
      DB_USER: postgres
      DB_PASSWORD: password2
      # IMPORTANT: change username and password for deployment
      # might need to comment these out when restarting keycloak
      KEYCLOAK_USER: admin
      KEYCLOAK_PASSWORD: admin
      DB_SCHEMA: public
      PROXY_ADDRESS_FORWARDING: 'true'
      # KEYCLOAK_LOGLEVEL: ALL
      KEYCLOAK_IMPORT: /tmp/realm-export.json # comment this line if you don't want the default realm to be imported
    depends_on:
      - keycloak_db
    restart: always

  keycloak_db:
    image: postgres:12
    volumes:
      - keycloak_db:/var/lib/postgresql/data
    environment:
      # default user is 'postgres'
      POSTGRES_DB: keycloak_db
      POSTGRES_PASSWORD: password2
    restart: always

  middleware-redis:
    image: redis
    restart: always

  middleware-db:
    image: postgres:12
    volumes:
      - middleware_db:/var/lib/postgresql/data
    environment:
      # default user and DB is postgres
      POSTGRES_PASSWORD: password
    restart: always

  keycloakextensionapi:
    image: irpinesctec/keycloak_extension_api:0.1.0
    environment:
      DB_DATABASE: keycloak_db
      DB_USER: postgres
      DB_PASSWORD: password2
      DB_HOST: keycloak_db
      DB_PORT: 5432
      KEYCLOAK_URL: https://trialreceptor.inesctec.pt/auth/
      REALM: master
    restart: always

volumes:
  keycloak_db:
  middleware_db: