version: '3'

services:
  repository-db:
    image: ireceptor/repository-mongodb:master
    volumes:
        - ./data/mongodb:/data/db:delegated
    environment:
        MONGO_INITDB_DATABASE: ireceptor
    restart: always

  repository:
    image: ireceptor/service-php-mongodb:master
    environment:
        DB_HOST: repository-db
        DB_DATABASE: ireceptor
        DB_SAMPLES_COLLECTION: sample
        DB_SEQUENCES_COLLECTION: sequence
        IRECEPTOR_AIRR_MAPPING_FILE: files/AIRR-iReceptorMapping.txt
    volumes:
        - ./config/turnkey:/var/www/html/config/files:delegated
    depends_on:
      - repository-db
    restart: always

  middleware:
    image: irpinesctec/adc-middleware
    volumes:
      - ./config/middleware:/middleware/config
    environment:
      - UMA_CLIENT_SECRET=$MIDDLEWARE_UMA_CLIENT_SECRET
      - DB_PASSWORD=password
      - PROPERTIES_PATH=/middleware/config/example.properties
    depends_on:
      - keycloak
      - middleware-db
      - middleware-redis
    restart: always

  keycloak:
    # based on: jboss/keycloak:12.0.4
    build: ./config/keycloak
    environment:
      DB_VENDOR: postgres
      DB_ADDR: keycloak_db
      DB_DATABASE: keycloak_db
      DB_USER: postgres
      DB_PASSWORD: password2
      # IMPORTANT: change username and password for deployment
      # might need to comment these out when restarting keycloak
      KEYCLOAK_USER: admin
      KEYCLOAK_PASSWORD: admin
      DB_SCHEMA: public
      PROXY_ADDRESS_FORWARDING: 'true'
      # KEYCLOAK_LOGLEVEL: ALL
    depends_on:
      - keycloak_db
    restart: always

  keycloak_db:
    image: postgres:12
    volumes:
      - keycloak_db:/var/lib/postgresql/data
    environment:
      # default user is 'postgres'
      POSTGRES_DB: keycloak_db
      POSTGRES_PASSWORD: password2
    restart: always

  middleware-redis:
    image: redis
    restart: always

  middleware-db:
    image: postgres:12
    volumes:
      - middleware_db:/var/lib/postgresql/data
    environment:
      # default user and DB is postgres
      POSTGRES_PASSWORD: password
    restart: always

  server:
    image: nginx
    volumes:
      - ./config/nginx/nginx.conf:/etc/nginx/nginx.conf:ro
    ports:
      - 80:80
    restart: always

  # up this container and then run
  # $ docker-compose exec http-logger /bin/sh
  # $ mitmproxy --mode reverse:http://keycloak:8080 -p 8081 --setheaders :~q:Host:http-logger:8081
  # http-logger:
  #   image: mitmproxy/mitmproxy
  #   stdin_open: true # docker run -i
  #   tty: true        # docker run -t
  #   entrypoint: /bin/sh
  #   ports:
  #     - 8081:8081

volumes:
  keycloak_db:
  middleware_db: