version: '3'

services:
  repository-db:
    image: ireceptor/repository-mongodb:master
    volumes:
        - ./tmp/mongodb:/data/db:delegated
    environment:
        MONGO_INITDB_DATABASE: ireceptor

  repository:
    depends_on:
        - repository-db
    image: ireceptor/service-php-mongodb:master
    environment:
        DB_HOST: repository-db
        DB_DATABASE: ireceptor
        DB_SAMPLES_COLLECTION: sample
        DB_SEQUENCES_COLLECTION: sequence
        IRECEPTOR_AIRR_MAPPING_FILE: files/AIRR-iReceptorMapping.txt
    volumes:
        - ./config/turnkey:/var/www/html/config/files:delegated
    ports:
        - 8000:80

  middleware:
    image: ros65536/adc-middleware
    volumes:
      - ./data/config:/middleware/config
    ports:
      - 8080:80
    environment:
      - UMA_CLIENT_SECRET=$MIDDLEWARE_UMA_CLIENT_SECRET
      - DB_PASSWORD=password
      - PROPERTIES_PATH=./config/example.properties
    depends_on:
      - keycloak
      - middleware-db
      - middleware-redis

  keycloak:
    image: jboss/keycloak:9.0.3
    environment:
      DB_VENDOR: postgres
      DB_ADDR: keycloak_db
      DB_DATABASE: keycloak_db
      DB_USER: postgres
      DB_PASSWORD: password2
      KEYCLOAK_USER: admin
      KEYCLOAK_PASSWORD: admin
      DB_SCHEMA: public
      PROXY_ADDRESS_FORWARDING: 'true'
    ports:
      - 8082:8080
    depends_on:
      - keycloak_db

  keycloak_db:
    image: postgres:12
    volumes:
      - ./data/db_keycloak:/var/lib/postgresql/data
    environment:
      # default user is 'postgres'
      POSTGRES_DB: keycloak_db
      POSTGRES_PASSWORD: password2

  middleware-redis:
    image: redis

  middleware-db:
    image: postgres:12
    volumes:
      - ./data/postgres:/var/lib/postgresql/data
    environment:
      # default user and DB is postgres
      POSTGRES_PASSWORD: password


