version: '3'

services:
  keycloak:
    build:
      context: keycloak
      dockerfile: dev.Dockerfile
    volumes:
      - ./tmp/keycloak_inner:/keycloak/standalone/data
    ports:
      - 8082:80
    depends_on:
      - keycloak_db


  keycloak_db:
    image: postgres:12
    volumes:
      - ./tmp/db_keycloak:/var/lib/postgresql/data
    environment:
      # default user is 'postgres'
      POSTGRES_DB: keycloak_db
      POSTGRES_PASSWORD: password2

  redis:
    image: redis
    ports:
      - 6379:6379

  db:
    image: postgres:12
    volumes:
      - ./tmp/postgres:/var/lib/postgresql/data
    ports:
      - 5432:5432
    environment:
      # default user is 'postgres'
      POSTGRES_DB: middleware_db
      POSTGRES_PASSWORD: password