version: '3'

services:
  keycloak:
    build:
      context: keycloak
      dockerfile: dev.Dockerfile
    volumes:
      - ./tmp/keycloak_inner:/keycloak/standalone/data:delegated
    ports:
      - 8082:80

  redis:
    image: redis
    ports:
      - 6379:6379

  db:
    image: postgres:12
    volumes:
      - ./tmp/postgres:/var/lib/postgresql/data:delegated
    ports:
      - 5432:5432
    environment:
      # default user is 'postgres'
      POSTGRES_DB: middleware_db
      POSTGRES_PASSWORD: password