version: '3'

services:
  keycloak:
    build:
      context: keycloak
      dockerfile: dev.Dockerfile
    volumes:
      - ./data/keycloak:/keycloak/standalone/data
    ports:
      - 8082:80

  redis:
    image: redis
    ports:
      - 6379:6379

  db:
    image: postgres:12
    volumes:
      - ./data/postgres:/var/lib/postgresql/data
    ports:
      - 5432:5432
    environment:
      # default user and DB is postgres
      POSTGRES_PASSWORD: password