version: '3'

services:
  keycloak_db:
    image: postgres
    volumes:
      - postgres_data:/var/lib/postgresql/data
    environment:
      POSTGRES_DB: keycloak
      POSTGRES_USER: keycloak
      POSTGRES_PASSWORD: password
    ports:
      - 5433:5432
    restart: always

  keycloak:
    build:
      context: ./keycloak
      dockerfile: Dockerfile
    volumes:
      ./example/keycloak/realm-export.json:/tmp/realm-export.json
    environment:
      DB_VENDOR: POSTGRES
      DB_ADDR: keycloak_db
      DB_DATABASE: keycloak
      DB_USER: keycloak
      DB_SCHEMA: public
      DB_PASSWORD: password
      KEYCLOAK_EXTRA_ARGS: "-Dkeycloak.profile.feature.upload_scripts=enabled"
      KEYCLOAK_USER: admin
      KEYCLOAK_PASSWORD: admin
      KEYCLOAK_IMPORT: /tmp/realm-export.json # comment this line if you don't want the default realm to be imported
    ports:
      - 8082:8080
    depends_on:
      - keycloak_db
    restart: always

  redis:
    image: redis
    ports:
      - 6379:6379
    restart: always

  keycloakextensionapi:
    image: irpinesctec/keycloak_extension_api:0.1.0
    environment:
      DB_DATABASE: keycloak
      DB_USER: keycloak
      DB_PASSWORD: password
      DB_HOST: keycloak_db
      DB_PORT: 5432
      KEYCLOAK_URL: http://keycloak:8080/auth/
      REALM: master
    restart: always
    ports:
      - 5454:8000

  db:
    image: postgres:12
    volumes:
      - middleware_db:/var/lib/postgresql/data:delegated
    ports:
      - 5432:5432
    environment:
      # default user is 'postgres'
      POSTGRES_DB: middleware_db
      POSTGRES_PASSWORD: password
    restart: always

volumes:
  middleware_db:

  postgres_data:
    driver: local
