version: '3'

services:
  middleware:
#    build: .
    image: ros65536/adc-middleware
    volumes:
      - ./data/config:/middleware/config
    ports:
      - 8080:80
    environment:
      - CLIENT_SECRET=$MIDDLEWARE_UMA_CLIENT_SECRET
    depends_on:
      - keycloak
      - middleware-db
    networks:
      - turnkey-service_default

  keycloak:
    build:
      context: keycloak
      dockerfile: dev.Dockerfile
    volumes:
      - ./data/keycloak:/keycloak/standalone/data
    ports:
      - 8082:80
    networks:
      - turnkey-service_default

  middleware-redis:
    image: redis
    networks:
      - turnkey-service_default

  middleware-db:
    image: postgres:12
    volumes:
      - ./data/postgres:/var/lib/postgresql/data
    environment:
      # default user and DB is postgres
      POSTGRES_PASSWORD: password
    networks:
      - turnkey-service_default

networks:
  turnkey-service_default:
    external: true


