version: '3'

services:
  keycloak:
    image: jboss/keycloak:9.0.3
    environment:
      DB_VENDOR: postgres
      DB_ADDR: keycloak_db
      DB_DATABASE: keycloak_db
      DB_USER: postgres
      DB_PASSWORD: password2
      KEYCLOAK_USER: admin
      KEYCLOAK_PASSWORD: admin
      DB_SCHEMA: public
      PROXY_ADDRESS_FORWARDING: 'true'
    ports:
      - 8082:8080
    depends_on:
      - keycloak_db


  keycloak_db:
    image: postgres:12
    volumes:
      - ./tmp/db_keycloak:/var/lib/postgresql/data
    environment:
      # default user is 'postgres'
      POSTGRES_DB: keycloak_db
      POSTGRES_PASSWORD: password2

  redis:
    image: redis
    ports:
      - 6379:6379

  db:
    image: postgres:12
    volumes:
      - ./tmp/postgres:/var/lib/postgresql/data
    ports:
      - 5432:5432
    environment:
      # default user is 'postgres'
      POSTGRES_DB: middleware_db
      POSTGRES_PASSWORD: password