CREATE OR REPLACE FUNCTION pg_temp.get_scope_id(scope_name VARCHAR)
  RETURNS INT AS
$func$
    SELECT id FROM access_scope WHERE "name" = scope_name;
$func$ LANGUAGE sql;

CREATE OR REPLACE FUNCTION pg_temp.get_adc_field_id(field_type VARCHAR, field_name VARCHAR)
  RETURNS INT AS
$func$
    SELECT af.id FROM adc_fields af
    INNER JOIN adc_field_type ft ON af.id_type = ft.id
    WHERE af."name" = field_name AND ft."name" = field_type;
$func$ LANGUAGE sql;

DO $$
DECLARE
    -- Holders for insertion IDs
    template_id  INT;
    adc_id INT;
    scope_id INT;

    -- Field mappings
    arr_fields   VARCHAR[] := array[
        ['repertoire', 'repertoire_id', 'public'],
        ['repertoire', 'repertoire_name', 'public'],
        ['repertoire', 'repertoire_description', 'public'],
        ['repertoire', 'study.study_id', 'public'],
        ['repertoire', 'study.study_title', 'public'],
        ['repertoire', 'study.study_type.value', 'statistics'],
        ['repertoire', 'study.study_type.id', 'statistics'],
        ['repertoire', 'study.study_description', 'statistics'],
        ['repertoire', 'study.inclusion_exclusion_criteria', 'statistics'],
        ['repertoire', 'study.grants', 'statistics'],
        ['repertoire', 'study.collected_by', 'statistics'],
        ['repertoire', 'study.lab_name', 'statistics'],
        ['repertoire', 'study.lab_address', 'statistics'],
        ['repertoire', 'study.submitted_by', 'statistics'],
        ['repertoire', 'study.pub_ids', 'statistics'],
        ['repertoire', 'study.keywords_study', 'statistics'],
        ['repertoire', 'subject.subject_id', 'statistics'],
        ['repertoire', 'subject.synthetic', 'statistics'],
        ['repertoire', 'subject.organism.value', 'statistics'],
        ['repertoire', 'subject.organism.id', 'statistics'],
        ['repertoire', 'subject.sex', 'statistics'],
        ['repertoire', 'subject.age_min', 'statistics'],
        ['repertoire', 'subject.age_max', 'statistics'],
        ['repertoire', 'subject.age_unit.value', 'statistics'],
        ['repertoire', 'subject.age_unit.id', 'statistics'],
        ['repertoire', 'subject.age_event', 'statistics'],
        ['repertoire', 'subject.age', 'statistics'],
        ['repertoire', 'subject.ancestry_population', 'statistics'],
        ['repertoire', 'subject.ethnicity', 'statistics'],
        ['repertoire', 'subject.race', 'statistics'],
        ['repertoire', 'subject.strain_name', 'statistics'],
        ['repertoire', 'subject.linked_subjects', 'statistics'],
        ['repertoire', 'subject.link_type', 'statistics'],
        ['repertoire', 'subject.diagnosis.study_group_description', 'statistics'],
        ['repertoire', 'subject.diagnosis.disease_diagnosis', 'statistics'],
        ['repertoire', 'subject.diagnosis.disease_length', 'statistics'],
        ['repertoire', 'subject.diagnosis.disease_stage', 'statistics'],
        ['repertoire', 'subject.diagnosis.prior_therapies', 'statistics'],
        ['repertoire', 'subject.diagnosis.immunogen', 'statistics'],
        ['repertoire', 'subject.diagnosis.intervention', 'statistics'],
        ['repertoire', 'subject.diagnosis.medical_history', 'statistics'],
        ['repertoire', 'sample.sample_id', 'raw_sequence'],
        ['repertoire', 'sample.sample_type', 'raw_sequence'],
        ['repertoire', 'sample.tissue', 'raw_sequence'],
        ['repertoire', 'sample.anatomic_site', 'raw_sequence'],
        ['repertoire', 'sample.disease_state_sample', 'raw_sequence'],
        ['repertoire', 'sample.collection_time_point_relative', 'raw_sequence'],
        ['repertoire', 'sample.collection_time_point_reference', 'raw_sequence'],
        ['repertoire', 'sample.biomaterial_provider', 'raw_sequence'],
        ['repertoire', 'sample.tissue_processing', 'raw_sequence'],
        ['repertoire', 'sample.cell_subset.value', 'raw_sequence'],
        ['repertoire', 'sample.cell_subset.id', 'raw_sequence'],
        ['repertoire', 'sample.cell_phenotype', 'raw_sequence'],
        ['repertoire', 'sample.cell_species.value', 'raw_sequence'],
        ['repertoire', 'sample.cell_species.id', 'raw_sequence'],
        ['repertoire', 'sample.single_cell', 'raw_sequence'],
        ['repertoire', 'sample.cell_number', 'raw_sequence'],
        ['repertoire', 'sample.cells_per_reaction', 'raw_sequence'],
        ['repertoire', 'sample.cell_storage', 'raw_sequence'],
        ['repertoire', 'sample.cell_quality', 'raw_sequence'],
        ['repertoire', 'sample.cell_isolation', 'raw_sequence'],
        ['repertoire', 'sample.cell_processing_protocol', 'raw_sequence'],
        ['repertoire', 'sample.template_class', 'raw_sequence'],
        ['repertoire', 'sample.template_quality', 'raw_sequence'],
        ['repertoire', 'sample.template_amount', 'raw_sequence'],
        ['repertoire', 'sample.library_generation_method', 'raw_sequence'],
        ['repertoire', 'sample.library_generation_protocol', 'raw_sequence'],
        ['repertoire', 'sample.library_generation_kit_version', 'raw_sequence'],
        ['repertoire', 'sample.pcr_target.pcr_target_locus', 'raw_sequence'],
        ['repertoire', 'sample.pcr_target.forward_pcr_primer_target_location', 'raw_sequence'],
        ['repertoire', 'sample.pcr_target.reverse_pcr_primer_target_location', 'raw_sequence'],
        ['repertoire', 'sample.complete_sequences', 'raw_sequence'],
        ['repertoire', 'sample.physical_linkage', 'raw_sequence'],
        ['repertoire', 'sample.sequencing_run_id', 'raw_sequence'],
        ['repertoire', 'sample.total_reads_passing_qc_filter', 'raw_sequence'],
        ['repertoire', 'sample.sequencing_platform', 'raw_sequence'],
        ['repertoire', 'sample.sequencing_facility', 'raw_sequence'],
        ['repertoire', 'sample.sequencing_run_date', 'raw_sequence'],
        ['repertoire', 'sample.sequencing_kit', 'raw_sequence'],
        ['repertoire', 'sample.sequencing_files.file_type', 'raw_sequence'],
        ['repertoire', 'sample.sequencing_files.filename', 'raw_sequence'],
        ['repertoire', 'sample.sequencing_files.read_direction', 'raw_sequence'],
        ['repertoire', 'sample.sequencing_files.read_length', 'raw_sequence'],
        ['repertoire', 'sample.sequencing_files.paired_filename', 'raw_sequence'],
        ['repertoire', 'sample.sequencing_files.paired_read_direction', 'raw_sequence'],
        ['repertoire', 'sample.sequencing_files.paired_read_length', 'raw_sequence'],
        ['repertoire', 'data_processing.data_processing_id', 'statistics'],
        ['repertoire', 'data_processing.primary_annotation', 'statistics'],
        ['repertoire', 'data_processing.software_versions', 'statistics'],
        ['repertoire', 'data_processing.paired_reads_assembly', 'statistics'],
        ['repertoire', 'data_processing.quality_thresholds', 'statistics'],
        ['repertoire', 'data_processing.primer_match_cutoffs', 'statistics'],
        ['repertoire', 'data_processing.collapsing_method', 'statistics'],
        ['repertoire', 'data_processing.data_processing_protocols', 'statistics'],
        ['repertoire', 'data_processing.data_processing_files', 'statistics'],
        ['repertoire', 'data_processing.germline_database', 'statistics'],
        ['repertoire', 'data_processing.analysis_provenance_id', 'statistics'],

        ['rearrangement', 'sequence_id', 'raw_sequence'],
        ['rearrangement', 'sequence', 'raw_sequence'],
        ['rearrangement', 'sequence_aa', 'raw_sequence'],
        ['rearrangement', 'rev_comp', 'raw_sequence'],
        ['rearrangement', 'productive', 'raw_sequence'],
        ['rearrangement', 'vj_in_frame', 'raw_sequence'],
        ['rearrangement', 'stop_codon', 'raw_sequence'],
        ['rearrangement', 'complete_vdj', 'raw_sequence'],
        ['rearrangement', 'locus', 'raw_sequence'],
        ['rearrangement', 'v_call', 'raw_sequence'],
        ['rearrangement', 'd_call', 'raw_sequence'],
        ['rearrangement', 'd2_call', 'raw_sequence'],
        ['rearrangement', 'j_call', 'raw_sequence'],
        ['rearrangement', 'c_call', 'raw_sequence'],
        ['rearrangement', 'sequence_alignment', 'raw_sequence'],
        ['rearrangement', 'sequence_alignment_aa', 'raw_sequence'],
        ['rearrangement', 'germline_alignment', 'raw_sequence'],
        ['rearrangement', 'germline_alignment_aa', 'raw_sequence'],
        ['rearrangement', 'junction', 'raw_sequence'],
        ['rearrangement', 'junction_aa', 'raw_sequence'],
        ['rearrangement', 'np1', 'raw_sequence'],
        ['rearrangement', 'np1_aa', 'raw_sequence'],
        ['rearrangement', 'np2', 'raw_sequence'],
        ['rearrangement', 'np2_aa', 'raw_sequence'],
        ['rearrangement', 'np3', 'raw_sequence'],
        ['rearrangement', 'np3_aa', 'raw_sequence'],
        ['rearrangement', 'cdr1', 'raw_sequence'],
        ['rearrangement', 'cdr1_aa', 'raw_sequence'],
        ['rearrangement', 'cdr2', 'raw_sequence'],
        ['rearrangement', 'cdr2_aa', 'raw_sequence'],
        ['rearrangement', 'cdr3', 'raw_sequence'],
        ['rearrangement', 'cdr3_aa', 'raw_sequence'],
        ['rearrangement', 'fwr1', 'raw_sequence'],
        ['rearrangement', 'fwr1_aa', 'raw_sequence'],
        ['rearrangement', 'fwr2', 'raw_sequence'],
        ['rearrangement', 'fwr2_aa', 'raw_sequence'],
        ['rearrangement', 'fwr3', 'raw_sequence'],
        ['rearrangement', 'fwr3_aa', 'raw_sequence'],
        ['rearrangement', 'fwr4', 'raw_sequence'],
        ['rearrangement', 'fwr4_aa', 'raw_sequence'],
        ['rearrangement', 'v_score', 'raw_sequence'],
        ['rearrangement', 'v_identity', 'raw_sequence'],
        ['rearrangement', 'v_support', 'raw_sequence'],
        ['rearrangement', 'v_cigar', 'raw_sequence'],
        ['rearrangement', 'd_score', 'raw_sequence'],
        ['rearrangement', 'd_identity', 'raw_sequence'],
        ['rearrangement', 'd_support', 'raw_sequence'],
        ['rearrangement', 'd_cigar', 'raw_sequence'],
        ['rearrangement', 'd2_score', 'raw_sequence'],
        ['rearrangement', 'd2_identity', 'raw_sequence'],
        ['rearrangement', 'd2_support', 'raw_sequence'],
        ['rearrangement', 'd2_cigar', 'raw_sequence'],
        ['rearrangement', 'j_score', 'raw_sequence'],
        ['rearrangement', 'j_identity', 'raw_sequence'],
        ['rearrangement', 'j_support', 'raw_sequence'],
        ['rearrangement', 'j_cigar', 'raw_sequence'],
        ['rearrangement', 'c_score', 'raw_sequence'],
        ['rearrangement', 'c_identity', 'raw_sequence'],
        ['rearrangement', 'c_support', 'raw_sequence'],
        ['rearrangement', 'c_cigar', 'raw_sequence'],
        ['rearrangement', 'v_sequence_start', 'raw_sequence'],
        ['rearrangement', 'v_sequence_end', 'raw_sequence'],
        ['rearrangement', 'v_germline_start', 'raw_sequence'],
        ['rearrangement', 'v_germline_end', 'raw_sequence'],
        ['rearrangement', 'v_alignment_start', 'raw_sequence'],
        ['rearrangement', 'v_alignment_end', 'raw_sequence'],
        ['rearrangement', 'd_sequence_start', 'raw_sequence'],
        ['rearrangement', 'd_sequence_end', 'raw_sequence'],
        ['rearrangement', 'd_germline_start', 'raw_sequence'],
        ['rearrangement', 'd_germline_end', 'raw_sequence'],
        ['rearrangement', 'd_alignment_start', 'raw_sequence'],
        ['rearrangement', 'd_alignment_end', 'raw_sequence'],
        ['rearrangement', 'd2_sequence_start', 'raw_sequence'],
        ['rearrangement', 'd2_sequence_end', 'raw_sequence'],
        ['rearrangement', 'd2_germline_start', 'raw_sequence'],
        ['rearrangement', 'd2_germline_end', 'raw_sequence'],
        ['rearrangement', 'd2_alignment_start', 'raw_sequence'],
        ['rearrangement', 'd2_alignment_end', 'raw_sequence'],
        ['rearrangement', 'j_sequence_start', 'raw_sequence'],
        ['rearrangement', 'j_sequence_end', 'raw_sequence'],
        ['rearrangement', 'j_germline_start', 'raw_sequence'],
        ['rearrangement', 'j_germline_end', 'raw_sequence'],
        ['rearrangement', 'j_alignment_start', 'raw_sequence'],
        ['rearrangement', 'j_alignment_end', 'raw_sequence'],
        ['rearrangement', 'cdr1_start', 'raw_sequence'],
        ['rearrangement', 'cdr1_end', 'raw_sequence'],
        ['rearrangement', 'cdr2_start', 'raw_sequence'],
        ['rearrangement', 'cdr2_end', 'raw_sequence'],
        ['rearrangement', 'cdr3_start', 'raw_sequence'],
        ['rearrangement', 'cdr3_end', 'raw_sequence'],
        ['rearrangement', 'fwr1_start', 'raw_sequence'],
        ['rearrangement', 'fwr1_end', 'raw_sequence'],
        ['rearrangement', 'fwr2_start', 'raw_sequence'],
        ['rearrangement', 'fwr2_end', 'raw_sequence'],
        ['rearrangement', 'fwr3_start', 'raw_sequence'],
        ['rearrangement', 'fwr3_end', 'raw_sequence'],
        ['rearrangement', 'fwr4_start', 'raw_sequence'],
        ['rearrangement', 'fwr4_end', 'raw_sequence'],
        ['rearrangement', 'v_sequence_alignment', 'raw_sequence'],
        ['rearrangement', 'v_sequence_alignment_aa', 'raw_sequence'],
        ['rearrangement', 'd_sequence_alignment', 'raw_sequence'],
        ['rearrangement', 'd_sequence_alignment_aa', 'raw_sequence'],
        ['rearrangement', 'd2_sequence_alignment', 'raw_sequence'],
        ['rearrangement', 'd2_sequence_alignment_aa', 'raw_sequence'],
        ['rearrangement', 'j_sequence_alignment', 'raw_sequence'],
        ['rearrangement', 'j_sequence_alignment_aa', 'raw_sequence'],
        ['rearrangement', 'c_sequence_alignment', 'raw_sequence'],
        ['rearrangement', 'c_sequence_alignment_aa', 'raw_sequence'],
        ['rearrangement', 'v_germline_alignment', 'raw_sequence'],
        ['rearrangement', 'v_germline_alignment_aa', 'raw_sequence'],
        ['rearrangement', 'd_germline_alignment', 'raw_sequence'],
        ['rearrangement', 'd_germline_alignment_aa', 'raw_sequence'],
        ['rearrangement', 'd2_germline_alignment', 'raw_sequence'],
        ['rearrangement', 'd2_germline_alignment_aa', 'raw_sequence'],
        ['rearrangement', 'j_germline_alignment', 'raw_sequence'],
        ['rearrangement', 'j_germline_alignment_aa', 'raw_sequence'],
        ['rearrangement', 'c_germline_alignment', 'raw_sequence'],
        ['rearrangement', 'c_germline_alignment_aa', 'raw_sequence'],
        ['rearrangement', 'junction_length', 'raw_sequence'],
        ['rearrangement', 'junction_aa_length', 'raw_sequence'],
        ['rearrangement', 'np1_length', 'raw_sequence'],
        ['rearrangement', 'np2_length', 'raw_sequence'],
        ['rearrangement', 'np3_length', 'raw_sequence'],
        ['rearrangement', 'n1_length', 'raw_sequence'],
        ['rearrangement', 'n2_length', 'raw_sequence'],
        ['rearrangement', 'n3_length', 'raw_sequence'],
        ['rearrangement', 'p3v_length', 'raw_sequence'],
        ['rearrangement', 'p5d_length', 'raw_sequence'],
        ['rearrangement', 'p3d_length', 'raw_sequence'],
        ['rearrangement', 'p5d2_length', 'raw_sequence'],
        ['rearrangement', 'p3d2_length', 'raw_sequence'],
        ['rearrangement', 'p5j_length', 'raw_sequence'],
        ['rearrangement', 'consensus_count', 'raw_sequence'],
        ['rearrangement', 'duplicate_count', 'raw_sequence'],
        ['rearrangement', 'cell_id', 'raw_sequence'],
        ['rearrangement', 'clone_id', 'raw_sequence'],
        ['rearrangement', 'rearrangement_id', 'raw_sequence'],
        ['rearrangement', 'repertoire_id', 'raw_sequence'],
        ['rearrangement', 'sample_processing_id', 'raw_sequence'],
        ['rearrangement', 'data_processing_id', 'raw_sequence'],
        ['rearrangement', 'germline_database', 'raw_sequence']
     ];

    i VARCHAR[];
BEGIN
    INSERT INTO templates(name) VALUES ('default') RETURNING id INTO template_id;

    FOREACH i SLICE 1 IN ARRAY arr_fields
       LOOP
          SELECT pg_temp.get_adc_field_id(i[1], i[2]) INTO adc_id;
          SELECT pg_temp.get_scope_id(i[3]) INTO scope_id;

          INSERT INTO template_mappings(id_template, id_adc_field, id_access_scope)
          VALUES (template_id, adc_id, scope_id);
       END LOOP;
END $$