
DROP TABLE STUDY_MAP IF EXISTS;
-- This table is important to persist
CREATE TABLE STUDY_MAP (
    id INT AUTO_INCREMENT PRIMARY KEY,
    study_id VARCHAR(128) UNIQUE NOT NULL,
    uma_id VARCHAR(128) UNIQUE NOT NULL
);

DROP TABLE REPERTOIRE_MAP IF EXISTS;
CREATE TABLE REPERTOIRE_MAP (
    id INT AUTO_INCREMENT PRIMARY KEY,
    repertoire_id VARCHAR(128) UNIQUE NOT NULL,
    study_id INT NOT NULL,
    FOREIGN KEY (study_id) REFERENCES STUDY_MAP(id) ON DELETE CASCADE
);

DROP TABLE REARRANGEMENT_MAP IF EXISTS;
CREATE TABLE REARRANGEMENT_MAP (
    id INT AUTO_INCREMENT PRIMARY KEY,
    rearrangement_id VARCHAR(128) UNIQUE NOT NULL,
    repertoire_id INT NOT NULL,
    FOREIGN KEY (repertoire_id) REFERENCES REPERTOIRE_MAP(id) ON DELETE CASCADE
);
